### ISSUE TITLE
login

### ISSUE THREAD

**Issue by Tediace** [akbarsaladin36/phalcon4-crud-tutorial#1]
bang untuk login kok ga bisa ya? saya coba di localhost pake "http://localhost:8000/Auth/login"

**Comment by akbarsaladin36** [comment]
> bang untuk login kok ga bisa ya? saya coba di localhost pake "http://localhost:8000/Auth/login"

emang errornya apa ya mas ? boleh kirim screenshot nya mas ?

**Comment by akbarsaladin36** [comment]
sebelumnya dah buat databasenya belum mas @Tediace ?

**Comment by Tediace** [comment]
database nya saya seperti ini sih
![database](https://i.im.ge/2022/07/19/FFSIB9.png)
saya juga sudah edit di config nya
mohon bantuan nya mas @akbarsaladin36

**Comment by akbarsaladin36** [comment]
di project sudah saya update untuk tabel sqlnya. nanti bisa didownload untuk dijadikan acuan.

**Comment by Tediace** [comment]
oke siap mas saya coba dulu

**Comment by akbarsaladin36** [comment]
yoo mas

**Comment by Tediace** [comment]
saya sudah pake database yang mas update tadi... pas saya jalankan localhost di login saya menemukan error seperti ini
![login](https://i.im.ge/2022/07/19/FFscXY.png)

**Comment by akbarsaladin36** [comment]
coba discreenshot dulu mas kodingannya untuk file config.php, terus controller nya mas biar saya cek.

**Comment by akbarsaladin36** [comment]
kalau masih bingung juga lihat dokumentasinya di link di bawah ini:

https://docs.phalcon.io/4.0/en/db-models

**Comment by Tediace** [comment]
**config.php**
```
<?php

/*
 * Modified: prepend directory path of current file, because of this file own different ENV under between Apache and command line.
 * NOTE: please remove this comment.
 */
defined('BASE_PATH') || define('BASE_PATH', getenv('BASE_PATH') ?: realpath(dirname(__FILE__) . '/../..'));
defined('APP_PATH') || define('APP_PATH', BASE_PATH . '/app');

return new \Phalcon\Config([
    'database' => [
        'adapter'     => 'Mysql',
        'host'        => 'localhost',
        'username'    => 'root',
        'password'    => 'MyNewPass',
        'dbname'      => 'phalcon4_crud_tutorial',
        'charset'     => 'utf8',
    ],
    'application' => [
        'appDir'         => APP_PATH . '/',
        'controllersDir' => APP_PATH . '/controllers/',
        'modelsDir'      => APP_PATH . '/models/',
        'migrationsDir'  => APP_PATH . '/migrations/',
        'viewsDir'       => APP_PATH . '/views/',
        'pluginsDir'     => APP_PATH . '/plugins/',
        'libraryDir'     => APP_PATH . '/library/',
        'cacheDir'       => BASE_PATH . '/cache/',
        'baseUri'        => '/',
    ]
]);
```
**authcontroller**
```
<?php
declare(strict_types=1);

use Phalcon\Http\Request;
use Phalcon\Http\Response;
use Phalcon\Security;

class AuthController extends \Phalcon\Mvc\Controller
{

    public function registerAction()
    {
        $this->view->disable();

        $request = $this->request->getJsonRawBody();

        $user = new User;
        $user->user_username = $request->username;
        $user->user_password = $this->security->hash($request->password);
        $user->save();

        $response = new Response();
        $result = [
            'code' => 200,
            'response' => 'Success',
            'message' => 'Success registered user!',
            'data' => $user
        ];

        // return json_encode($result); --> ini menggunakan metode PHP untuk menampilkan JSON

        // menggunakan function dari Phalcon untuk menampilkan hasil bentuk JSON
        return $response->setJsonContent($result);
    }

    public function loginAction()
    {
        $this->view->disable();

        $credentials = $this->request->getJsonRawBody();
        $response = new Response();

        $username = $credentials->username;
        $password = $credentials->password;

        $user = User::findFirst("user_username = '$username'");

        // var_dump($user);die();

        if($user !== NULL) {
            $checkPassword = $this->security->checkHash($password, $user->user_password);
            if($checkPassword === true) {
                $this->session->set('user', [
                    'user_id' => $user->user_id,
                    'user_username' => $user->user_username
                ]);
                $result = [
                    'code' => 200,
                    'response' => 'Success',
                    'message' => 'Your username is succesfully login!',
                    'data' => $user
                ];
                $response->setStatusCode(200,'Success');
                return $response->setJsonContent($result);
            } else {
                $result = [
                    'code' => 400,
                    'response' => 'Failed',
                    'message' => 'Your password is not match. Please type your correct password!',
                    'data' => null
                ];
                $response->setStatusCode(400,'Password Mismatched');
                return $response->setJsonContent($result);
            }
        } else {
            // echo 'Your username is not registered. Please register a new user now!';
            $result = [
                'code' => 400,
                'response' => 'Failed',
                'message' => 'Your username is not registered. Please register a new user now!',
                'data' => null
            ];
            $response->setStatusCode(400,'Not Found');
            return $response->setJsonContent($result);
        }
    }

    public function logoutAction()
    {
        $this->view->disable();

        $this->session->destroy();

        echo 'Logout Successful!';
    }

}

```

untuk config saya hanya ubah database saya.... controller nya saya tidak ada ubah sama sekali

**Comment by akbarsaladin36** [comment]
boleh kirim kodingan file model User nya mas ?

**Comment by akbarsaladin36** [comment]
sebelumnya dah pernah install phalcon di project nya gak mas ?

**Comment by Tediace** [comment]
**model user**
``` 
<?php

class User extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     */
    public $user_id;

    /**
     *
     * @var string
     */
    public $user_username;

    /**
     *
     * @var string
     */
    public $user_password;

    /**
     *
     * @var string
     */
    public $user_email;

    /**
     *
     * @var string
     */
    public $user_first_name;

    /**
     *
     * @var string
     */
    public $user_last_name;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("phalcon4_crud_tutorial");
        $this->setSource("users");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return User[]|User|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null): \Phalcon\Mvc\Model\ResultsetInterface
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return User|\Phalcon\Mvc\Model\ResultInterface|\Phalcon\Mvc\ModelInterface|null
     */
    public static function findFirst($parameters = null): ?\Phalcon\Mvc\ModelInterface
    {
        return parent::findFirst($parameters);
    }

}
```
phalcon nya saya pakai versi 4.1.2 mas.... harus nya sudah sih

**Comment by akbarsaladin36** [comment]
mas test nya di postman kah ?

**Comment by akbarsaladin36** [comment]
> **config.php**
> 
> ```
> <?php
> 
> /*
>  * Modified: prepend directory path of current file, because of this file own different ENV under between Apache and command line.
>  * NOTE: please remove this comment.
>  */
> defined('BASE_PATH') || define('BASE_PATH', getenv('BASE_PATH') ?: realpath(dirname(__FILE__) . '/../..'));
> defined('APP_PATH') || define('APP_PATH', BASE_PATH . '/app');
> 
> return new \Phalcon\Config([
>     'database' => [
>         'adapter'     => 'Mysql',
>         'host'        => 'localhost',
>         'username'    => 'root',
>         'password'    => 'MyNewPass',
>         'dbname'      => 'phalcon4_crud_tutorial',
>         'charset'     => 'utf8',
>     ],
>     'application' => [
>         'appDir'         => APP_PATH . '/',
>         'controllersDir' => APP_PATH . '/controllers/',
>         'modelsDir'      => APP_PATH . '/models/',
>         'migrationsDir'  => APP_PATH . '/migrations/',
>         'viewsDir'       => APP_PATH . '/views/',
>         'pluginsDir'     => APP_PATH . '/plugins/',
>         'libraryDir'     => APP_PATH . '/library/',
>         'cacheDir'       => BASE_PATH . '/cache/',
>         'baseUri'        => '/',
>     ]
> ]);
> ```
> 
> **authcontroller**
> 
> ```
> <?php
> declare(strict_types=1);
> 
> use Phalcon\Http\Request;
> use Phalcon\Http\Response;
> use Phalcon\Security;
> 
> class AuthController extends \Phalcon\Mvc\Controller
> {
> 
>     public function registerAction()
>     {
>         $this->view->disable();
> 
>         $request = $this->request->getJsonRawBody();
> 
>         $user = new User;
>         $user->user_username = $request->username;
>         $user->user_password = $this->security->hash($request->password);
>         $user->save();
> 
>         $response = new Response();
>         $result = [
>             'code' => 200,
>             'response' => 'Success',
>             'message' => 'Success registered user!',
>             'data' => $user
>         ];
> 
>         // return json_encode($result); --> ini menggunakan metode PHP untuk menampilkan JSON
> 
>         // menggunakan function dari Phalcon untuk menampilkan hasil bentuk JSON
>         return $response->setJsonContent($result);
>     }
> 
>     public function loginAction()
>     {
>         $this->view->disable();
> 
>         $credentials = $this->request->getJsonRawBody();
>         $response = new Response();
> 
>         $username = $credentials->username;
>         $password = $credentials->password;
> 
>         $user = User::findFirst("user_username = '$username'");
> 
>         // var_dump($user);die();
> 
>         if($user !== NULL) {
>             $checkPassword = $this->security->checkHash($password, $user->user_password);
>             if($checkPassword === true) {
>                 $this->session->set('user', [
>                     'user_id' => $user->user_id,
>                     'user_username' => $user->user_username
>                 ]);
>                 $result = [
>                     'code' => 200,
>                     'response' => 'Success',
>                     'message' => 'Your username is succesfully login!',
>                     'data' => $user
>                 ];
>                 $response->setStatusCode(200,'Success');
>                 return $response->setJsonContent($result);
>             } else {
>                 $result = [
>                     'code' => 400,
>                     'response' => 'Failed',
>                     'message' => 'Your password is not match. Please type your correct password!',
>                     'data' => null
>                 ];
>                 $response->setStatusCode(400,'Password Mismatched');
>                 return $response->setJsonContent($result);
>             }
>         } else {
>             // echo 'Your username is not registered. Please register a new user now!';
>             $result = [
>                 'code' => 400,
>                 'response' => 'Failed',
>                 'message' => 'Your username is not registered. Please register a new user now!',
>                 'data' => null
>             ];
>             $response->setStatusCode(400,'Not Found');
>             return $response->setJsonContent($result);
>         }
>     }
> 
>     public function logoutAction()
>     {
>         $this->view->disable();
> 
>         $this->session->destroy();
> 
>         echo 'Logout Successful!';
>     }
> 
> }
> ```
> 
> untuk config saya hanya ubah database saya.... controller nya saya tidak ada ubah sama sekali

matiin dulu server projectnya mas. terus coba yang bagian password di file config.php nya dihapus aja valuenya. abis itu diaktifkan lagi server projectnya di terminal mas.

**Comment by Tediace** [comment]
saya jalankan nya di command line saja mas... jadi tidak pakai postman
jika menjalankan "php -S localhost:8000 -t .htrouter.php -t public" bisa mas...
cuman untuk login ga bisa

**Comment by akbarsaladin36** [comment]
kalau untuk login coba test di postman mas. kan ada dokumentasi api postman yang saya lampirkan di project ini nanti bisa dicek dari situ mas.

**Comment by Tediace** [comment]
> php -S localhost:8000 -t .htrouter.php -t public

okee siapp mas

**Comment by Tediace** [comment]
> kalau untuk login coba test di postman mas. kan ada dokumentasi api postman yang saya lampirkan di project ini nanti bisa dicek dari situ mas.

okee siapp mas

**Comment by akbarsaladin36** [comment]
untuk method post dan update di postman form tipe JSON.

**Comment by Tediace** [comment]
> untuk method post dan update di postman form tipe JSON.

untuk kedepannya kodingan mas ya bisa di pakai UI di website tidak ya?
soal nya saya mau buat project website pakai phalcon 4 crud

**Comment by akbarsaladin36** [comment]
> > untuk method post dan update di postman form tipe JSON.
> 
> untuk kedepannya kodingan mas ya bisa di pakai UI di website tidak ya? soal nya saya mau buat project website pakai phalcon 4 crud

sebenarnya project saya ini untuk api backend. frontend nya bisa pake vue atau reactjs. tapi kalo untuk dipakai di UI dengan project ini bisa juga cuma harus diubah kodingan pada controllernya.

**Comment by Tediace** [comment]
okay siap mas makasih banyak atas bantuan nya.. sukses selalu

**Comment by akbarsaladin36** [comment]
sama2 mas

yang tadi terkait login gimana mas apakah ada kendala tadi ?

**Comment by Tediace** [comment]
> sama2 mas
> 
> yang tadi terkait login gimana mas apakah ada kendala tadi ?

saya coba dulu mas di postman... nanti saya kabari lagi

**Comment by akbarsaladin36** [comment]
oke mas @Tediace

**Comment by Tediace** [comment]
mas @akbarsaladin36 untuk login nya masih blm bisa... tapi untuk register nya sudah aman

```
Column 'user_username' doesn't belong to any of the selected models (1), when preparing: SELECT [User].* FROM [User]
WHERE user_username = 'admin' LIMIT :APL0:<br>
<pre>#0 [internal function]: Phalcon\Mvc\Model\Query->_getQualified(Array)
#1 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array, true)
#2 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array)
#3 [internal function]: Phalcon\Mvc\Model\Query->_prepareSelect()
#4 [internal function]: Phalcon\Mvc\Model\Query->parse()
#5 [internal function]: Phalcon\Mvc\Model\Query->execute()
#6 C:\Users\Tedi\Desktop\phalcon4-crud-tutorial\app\models\User.php(70): Phalcon\Mvc\Model::findFirst('user_username =...')
#7 C:\Users\Tedi\Desktop\phalcon4-crud-tutorial\app\controllers\AuthController.php(46): User::findFirst('user_username =...')
#8 [internal function]: AuthController->loginAction()
#9 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(AuthController), 'loginAction', Array)
#10 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#11 C:\Users\Tedi\Desktop\phalcon4-crud-tutorial\public\index.php(43): Phalcon\Mvc\Application->handle('/Auth/login?=')
#12 {main}</pre>
```

**Comment by akbarsaladin36** [comment]
saya coba cek bentar ya mas

**Comment by akbarsaladin36** [comment]
boleh lihat kodingan model sama screenshot database nya mas @Tediace ?

**Comment by Tediace** [comment]
**database**
![123](https://i.im.ge/2022/07/25/FIaXHf.png)
**model user**
```<?php

class User extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     */
    public $user_id;

    /**
     *
     * @var string
     */
    public $user_username;

    /**
     *
     * @var string
     */
    public $user_password;

    /**
     *
     * @var string
     */
    public $user_email;

    /**
     *
     * @var string
     */
    public $user_first_name;

    /**
     *
     * @var string
     */
    public $user_last_name;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("phalcon4_crud_tutorial");
        $this->setSource("users");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return User[]|User|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null): \Phalcon\Mvc\Model\ResultsetInterface
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return User|\Phalcon\Mvc\Model\ResultInterface|\Phalcon\Mvc\ModelInterface|null
     */
    public static function findFirst($parameters = null): ?\Phalcon\Mvc\ModelInterface
    {
        return parent::findFirst($parameters);
    }

}
```

**Comment by akbarsaladin36** [comment]
> **database** ![123](https://camo.githubusercontent.com/1f8cbcaa159e293f50e10e47f313406e6009d0e92a2402de291cb2b2cda2e422/68747470733a2f2f692e696d2e67652f323032322f30372f32352f4649736e5a442e706e67)
> 
> **model user**
> 
> ```
> 
> class User extends \Phalcon\Mvc\Model
> {
> 
>     /**
>      *
>      * @var integer
>      */
>     public $user_id;
> 
>     /**
>      *
>      * @var string
>      */
>     public $user_username;
> 
>     /**
>      *
>      * @var string
>      */
>     public $user_password;
> 
>     /**
>      *
>      * @var string
>      */
>     public $user_email;
> 
>     /**
>      *
>      * @var string
>      */
>     public $user_first_name;
> 
>     /**
>      *
>      * @var string
>      */
>     public $user_last_name;
> 
>     /**
>      * Initialize method for model.
>      */
>     public function initialize()
>     {
>         $this->setSchema("phalcon4_crud_tutorial");
>         $this->setSource("users");
>     }
> 
>     /**
>      * Allows to query a set of records that match the specified conditions
>      *
>      * @param mixed $parameters
>      * @return User[]|User|\Phalcon\Mvc\Model\ResultSetInterface
>      */
>     public static function find($parameters = null): \Phalcon\Mvc\Model\ResultsetInterface
>     {
>         return parent::find($parameters);
>     }
> 
>     /**
>      * Allows to query the first record that match the specified conditions
>      *
>      * @param mixed $parameters
>      * @return User|\Phalcon\Mvc\Model\ResultInterface|\Phalcon\Mvc\ModelInterface|null
>      */
>     public static function findFirst($parameters = null): ?\Phalcon\Mvc\ModelInterface
>     {
>         return parent::findFirst($parameters);
>     }
> 
> }
> ```

Fixed :

class User extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     */
    public $id;

    /**
     *
     * @var string
     */
    public $username;

    /**
     *
     * @var string
     */
    public $password;

    /**
     *
     * @var string
     */
    public $email;


    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("phalcon4_crud_tutorial");
        $this->setSource("users");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return User[]|User|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null): \Phalcon\Mvc\Model\ResultsetInterface
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return User|\Phalcon\Mvc\Model\ResultInterface|\Phalcon\Mvc\ModelInterface|null
     */
    public static function findFirst($parameters = null): ?\Phalcon\Mvc\ModelInterface
    {
        return parent::findFirst($parameters);
    }

}

sesuaikan dengan yang di kolom tabel di database untuk modelnya mas @Tediace

**Comment by Tediace** [comment]
oke mas udah ada perubahan... minta tolong authcontroller nya di review punya saya mas
```
<?php
declare(strict_types=1);

use Phalcon\Http\Request;
use Phalcon\Http\Response;
use Phalcon\Security;

class AuthController extends \Phalcon\Mvc\Controller
{

    public function registerAction()
    {
        $this->view->disable();

        $request = $this->request->getJsonRawBody();

        $user = new User;
        $user->username = $request->username;
        $user->password = $this->security->hash($request->password);
        $user->save();

        $response = new Response();
        $result = [
            'code' => 200,
            'response' => 'Success',
            'message' => 'Success registered user!',
            'data' => $user
        ];

        // return json_encode($result); --> ini menggunakan metode PHP untuk menampilkan JSON

        // menggunakan function dari Phalcon untuk menampilkan hasil bentuk JSON
        return $response->setJsonContent($result);
    }

    public function loginAction()
    {
        $this->view->disable();

        $credentials = $this->request->getJsonRawBody();
        $response = new Response();

        $username = $credentials->username;
        $password = $credentials->password;

        $user = User::findFirst("user_username = '$username'");

        // var_dump($user);die();

        if($user !== NULL) {
            $checkPassword = $this->security->checkHash($password, $user->user_password);
            if($checkPassword === true) {
                $this->session->set('user', [
                    'user_id' => $user->user_id,
                    'user_username' => $user->user_username
                ]);
                $result = [
                    'code' => 200,
                    'response' => 'Success',
                    'message' => 'Your username is succesfully login!',
                    'data' => $user
                ];
                $response->setStatusCode(200,'Success');
                return $response->setJsonContent($result);
            } else {
                $result = [
                    'code' => 400,
                    'response' => 'Failed',
                    'message' => 'Your password is not match. Please type your correct password!',
                    'data' => null
                ];
                $response->setStatusCode(400,'Password Mismatched');
                return $response->setJsonContent($result);
            }
        } else {
            // echo 'Your username is not registered. Please register a new user now!';
            $result = [
                'code' => 400,
                'response' => 'Failed',
                'message' => 'Your username is not registered. Please register a new user now!',
                'data' => null
            ];
            $response->setStatusCode(400,'Not Found');
            return $response->setJsonContent($result);
        }
    }

    public function logoutAction()
    {
        $this->view->disable();

        $this->session->destroy();

        echo 'Logout Successful!';
    }

}

```

**Comment by akbarsaladin36** [comment]
saya udah update untuk bagian login di auth controller nya. nanti bisa dilihat aja di situ mas.

**Comment by akbarsaladin36** [comment]
> user_password

bagian "user_username" diganti jadi "username" dan bagian "$user->user_password" diganti jadi "$user->password" di function loginAction nya setelah itu coba dicek mas @Tediace

**Comment by Tediace** [comment]
> > user_password
> 
> bagian "user_username" diganti jadi "username" dan bagian "$user->user_password" diganti jadi "$user->password" di function loginAction nya setelah itu coba dicek mas @Tediace
```
{
    "code": 400,
    "response": "Failed",
    "message": "Your username is not registered. Please register a new user now!",
    "data": null
}
```

jika seperti ini sudah bisa blm mas... atau username nya harus kita ganti juga biar dapat respon yang benar?

**Comment by Tediace** [comment]
ini untuk codingan login nya
```
public function loginAction()
    {
        $this->view->disable();

        $credentials = $this->request->getJsonRawBody();
        $response = new Response();

        $username = $credentials->username;
        $password = $credentials->password;

        // $user = User::findFirst("user_username = '$username'");

        $user = User::findFirst([
            'conditions' => 'username = :username:',
            'bind' => [
                'username' => $username
            ]
        ]);

        // var_dump($user);die();

        if($user !== NULL) {
            $checkPassword = $this->security->checkHash($password, $user->password);
            if($checkPassword === true) {
                $this->session->set('admin', [
                    'id' => $user->id,
                    'admin' => $user->admin
                ]);
                $result = [
                    'code' => 200,
                    'response' => 'Success',
                    'message' => 'Your username is succesfully login!',
                    'data' => $user
                ];
                $response->setStatusCode(200,'Success');
                return $response->setJsonContent($result);
            } else {
                $result = [
                    'code' => 400,
                    'response' => 'Failed',
                    'message' => 'Your password is not match. Please type your correct password!',
                    'data' => null
                ];
                $response->setStatusCode(400,'Password Mismatched');
                return $response->setJsonContent($result);
            }
        } else {
            // echo 'Your username is not registered. Please register a new user now!';
            $result = [
                'code' => 400,
                'response' => 'Failed',
                'message' => 'Your username is not registered. Please register a new user now!',
                'data' => null
            ];
            $response->setStatusCode(400,'Not Found');
            return $response->setJsonContent($result);
        }
    }

    public function logoutAction()
    {
        $this->view->disable();

        $this->session->destroy();

        echo 'Logout Successful!';
    }

}

```

**Comment by akbarsaladin36** [comment]
> > > user_password
> > 
> > 
> > bagian "user_username" diganti jadi "username" dan bagian "$user->user_password" diganti jadi "$user->password" di function loginAction nya setelah itu coba dicek mas @Tediace
> 
> ```
> {
>     "code": 400,
>     "response": "Failed",
>     "message": "Your username is not registered. Please register a new user now!",
>     "data": null
> }
> ```
> 
> jika seperti ini sudah bisa blm mas... atau username nya harus kita ganti juga biar dapat respon yang benar?

ini belum kedaftar usernya berarti mas. coba register aja dulu username baru mas.

**Comment by akbarsaladin36** [comment]
> ini untuk codingan login nya
> 
> ```
> public function loginAction()
>     {
>         $this->view->disable();
> 
>         $credentials = $this->request->getJsonRawBody();
>         $response = new Response();
> 
>         $username = $credentials->username;
>         $password = $credentials->password;
> 
>         // $user = User::findFirst("user_username = '$username'");
> 
>         $user = User::findFirst([
>             'conditions' => 'username = :username:',
>             'bind' => [
>                 'username' => $username
>             ]
>         ]);
> 
>         // var_dump($user);die();
> 
>         if($user !== NULL) {
>             $checkPassword = $this->security->checkHash($password, $user->password);
>             if($checkPassword === true) {
>                 $this->session->set('admin', [
>                     'id' => $user->id,
>                     'admin' => $user->admin
>                 ]);
>                 $result = [
>                     'code' => 200,
>                     'response' => 'Success',
>                     'message' => 'Your username is succesfully login!',
>                     'data' => $user
>                 ];
>                 $response->setStatusCode(200,'Success');
>                 return $response->setJsonContent($result);
>             } else {
>                 $result = [
>                     'code' => 400,
>                     'response' => 'Failed',
>                     'message' => 'Your password is not match. Please type your correct password!',
>                     'data' => null
>                 ];
>                 $response->setStatusCode(400,'Password Mismatched');
>                 return $response->setJsonContent($result);
>             }
>         } else {
>             // echo 'Your username is not registered. Please register a new user now!';
>             $result = [
>                 'code' => 400,
>                 'response' => 'Failed',
>                 'message' => 'Your username is not registered. Please register a new user now!',
>                 'data' => null
>             ];
>             $response->setStatusCode(400,'Not Found');
>             return $response->setJsonContent($result);
>         }
>     }
> 
>     public function logoutAction()
>     {
>         $this->view->disable();
> 
>         $this->session->destroy();
> 
>         echo 'Logout Successful!';
>     }
> 
> }
> ```

untuk $user->admin ada gak mas di database ? lebih bagus coba cek dulu value dari variabel $user dengan var_dump($user) ?

**Comment by Tediace** [comment]
harus nya jika sudah seperti ini sudah benar kan mas ya

```
{
    "code": 200,
    "response": "Success",
    "message": "Success registered user!",
    "data": {
        "id": null,
        "username": "admin",
        "password": "$2y$12$ajF4Z1h0U0VQaW5xdGZBVemMferRX9BWT/qvtI4VeFJMViHfxkRSm",
        "email": null
    }
}
```

tapi ketika saya jalan kan login tetap masih sama

**Comment by akbarsaladin36** [comment]
> 

itu kenapa id nya null ya ? harusnya otomatis ada di database. cek modelnya dulu mas

**Comment by akbarsaladin36** [comment]
coba screenshot schema database nya mas

**Comment by Tediace** [comment]
yang ini bukan mas...
![img1](https://i.im.ge/2022/07/25/FIRFih.png)

untuk id nya blm saya set ke autoincrement

**Comment by Tediace** [comment]
> > 
> 
> itu kenapa id nya null ya ? harusnya otomatis ada di database. cek modelnya dulu mas

untuk id nya sudah sesuai mas

**Comment by akbarsaladin36** [comment]
> yang ini bukan mas... ![img1](https://camo.githubusercontent.com/502590136f8c37ce0f79e3f118815402a0591bcbbeaed8851ddb2f9f55572323/68747470733a2f2f692e696d2e67652f323032322f30372f32352f4649524669682e706e67)
> 
> untuk id nya blm saya set ke autoincrement

Set ke auto increment dulu kolom idnya lalu coba register user baru terus login
